### ISSUE TITLE
Bintray-Artifacts missing

### ISSUE THREAD

**Issue by uhon** [antonkulaga/threejs-facade#11]
bintray-artifacts for version "0.0.77-0.1.7" as mentioned in README are unavailble.

artifact published on bintray has the version:
"0.0.74-0.1.7" 
See here: https://dl.bintray.com/denigma/denigma-releases/org/denigma/threejs-facade_sjs0.6_2.11/ 

Which three-js version is covered with 0.1.7? is it 0.0.77 or 0.0.74?

please clarify, thanks

**Comment by OndrejSpanel** [comment]
I confirm the issue, "0.0.77-0.1.7" is unresolved.

Can I help somehow to resolve it?

**Comment by OndrejSpanel** [comment]
No response, the facade looks abandoned now? The last published version contains serious issues, like what was fixed in PR #4 more than a year ago.

**Comment by antonkulaga** [comment]
@OndrejSpanel , @uhon , could you try 0.0.77-0.1.8 now? I published it for both Scala 2.12.

Regarding version numbers: <javascript_version>-<facade_itself_version>

**Comment by OndrejSpanel** [comment]
I confirm 0.77 is present now and can used fine.

**Comment by antonkulaga** [comment]
Great, I close the issue then.
