### ISSUE TITLE
failed to add resolver

### ISSUE THREAD

**Issue by oneengineer** [antonkulaga/threejs-facade#18]
I tried to add the text below to build.sbt.

resolvers += sbt.Resolver.bintrayRepo("denigma", "denigma-releases") //add resolver
libraryDependencies += "org.denigma" %%% "threejs-facade" % "0.0.77-0.1.8" //add dependency

But sbt cannot understand %%%, so I change it to %.

Then I got error
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.denigma#threejs-facade;0.0.77-0.1.8: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by PHo1975** [comment]
The resolvers and library dependencies work for me.
Did you add the scala-js sbt plugin to your plugins.sbt (http://www.scala-js.org/tutorial/basic/) and use the latest version of sbt ?

**Comment by oneengineer** [comment]
I forgot to add plugin...
