### ISSUE TITLE
Triggered start results in big compilation time.

### ISSUE THREAD

**Issue by ishubham-k** [antonkulaga/threejs-facade#7]
I was trying to play with the example source, so I started the triggered mode with `~re-start` command.  However whenever I change anything in the source it takes forever to compile and even after then the browser refresh shows the old files. Sometime back I was having exceptions on triggered start similar to this
`root [ERROR] [05/19/2016 18:58:48.928] [my-system-akka.actor.default-dispatcher-6] [akka://my-system/system/IO-TCP/selectors/$a/0] Bind failed for TCP channel on endpoint [/0.0.0.0:5
552]
root java.net.BindException: Address already in use: bind
root    at sun.nio.ch.Net.bind0(Native Method)
root    at sun.nio.ch.Net.bind(Net.java:433)
root    at sun.nio.ch.Net.bind(Net.java:425)
root    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
root    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
root    at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:53)
root    at akka.io.TcpListener.<init>(TcpListener.scala:50)
root    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
root    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
root    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
root    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
root    at akka.util.Reflect$.instantiate(Reflect.scala:65)
root    at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
root    at akka.actor.Props.newActor(Props.scala:214)
root    at akka.actor.ActorCell.newActor(ActorCell.scala:562)
root    at akka.actor.ActorCell.create(ActorCell.scala:588)
root    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
root    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
root    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
root    at akka.dispatch.Mailbox.run(Mailbox.scala:223)
root    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
root    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
root    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
root    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
root    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
root
root [DEBUG] [05/19/2016 18:58:48.934] [my-system-akka.actor.default-dispatcher-6] [akka://my-system/system/IO-TCP/selectors/$a/0] Closing serverSocketChannel after being stopped
[success] Total time: 123 s, completed 19 May, 2016 6:58:49 PM
3. Waiting for source changes... (press enter to interrupt)
`
However I was not able to reproduce it. 
These long compilation time makes it virtually impossible to make changes. I might be doing something wrong. Any suggestion would be helpful.

**Comment by antonkulaga** [comment]
This means that the port ( 5 552 ) you are trying to use is already used for something else, just change the port in configuration.
