### ISSUE TITLE
First load for preview gives blank page

### ISSUE THREAD

**Issue by ishubham-k** [antonkulaga/threejs-facade#9]
When I started the preview project with `sbt re-start` and entered `localhost:5552` in browser it showed the output as shown in screenshot. 
![error](https://cloud.githubusercontent.com/assets/8693515/15447084/70ceaf12-1f52-11e6-946f-dc2638a76e6f.png)
However on reloading the page again it works as expected.

**Comment by antonkulaga** [comment]
Looks outdated. Hope it works well for you now
